package com.hrishabh.algocracksubmissionservice.complexity.staticanalysis.model;

/**
 * Structured reason codes for static analysis completeness and confidence (Batch 0).
 */
public enum StaticAnalysisReasonCode {
    UNSUPPORTED_STATEMENT,
    UNSUPPORTED_EXPRESSION,
    UNVISITED_CHILD,
    OPAQUE_CALL,
    UNKNOWN_LOOP_BOUND,
    LOOP_PROGRESS_NOT_PROVEN,
    UNKNOWN_RECURSIVE_CYCLE,
    INCOMPLETE_TIME_ANALYSIS,
    INCOMPLETE_SPACE_ANALYSIS,
    UNDEFINED_SYMBOL,
    AMBIGUOUS_METHOD_TARGET,
    UNRESOLVED_HELPER_TARGET,
    UNSUPPORTED_RECURSIVE_SCC,
    UNSUPPORTED_RECURRENCE,
    RECURSION_PROGRESS_NOT_PROVEN,
    RECURSION_BASE_CASE_NOT_PROVEN,
    HELPER_SUMMARY_INCOMPLETE,
    CALLSITE_SUBSTITUTION_FAILED,
    JDK_TARGET_AMBIGUOUS,
    JDK_OPERATION_UNSUPPORTED,
    JDK_OVERLOAD_UNSUPPORTED,
    JDK_CARDINALITY_UNRESOLVED,
    JDK_CALLBACK_COST_UNRESOLVED,
    JDK_CALLSITE_SUBSTITUTION_FAILED,
    USER_TYPE_SHADOWS_JDK
}
