package com.hrishabh.algocracksubmissionservice.complexity.staticanalysis.model;

/**
 * Structured reason codes for static analysis completeness and confidence (Batch 0).
 */
public enum StaticAnalysisReasonCode {
    UNSUPPORTED_STATEMENT,
    UNSUPPORTED_EXPRESSION,
    UNVISITED_CHILD,
    OPAQUE_CALL,
    UNKNOWN_LOOP_BOUND,
    LOOP_PROGRESS_NOT_PROVEN,
    UNKNOWN_RECURSIVE_CYCLE,
    INCOMPLETE_TIME_ANALYSIS,
    INCOMPLETE_SPACE_ANALYSIS,
    UNDEFINED_SYMBOL,
    AMBIGUOUS_METHOD_TARGET,
    UNRESOLVED_HELPER_TARGET,
    UNSUPPORTED_RECURSIVE_SCC,
    UNSUPPORTED_RECURRENCE,
    RECURSION_PROGRESS_NOT_PROVEN,
    RECURSION_BASE_CASE_NOT_PROVEN,
    HELPER_SUMMARY_INCOMPLETE,
    CALLSITE_SUBSTITUTION_FAILED,
    JDK_TARGET_AMBIGUOUS,
    JDK_OPERATION_UNSUPPORTED,
    JDK_OVERLOAD_UNSUPPORTED,
    JDK_CARDINALITY_UNRESOLVED,
    JDK_CALLBACK_COST_UNRESOLVED,
    JDK_CALLSITE_SUBSTITUTION_FAILED,
    USER_TYPE_SHADOWS_JDK,
    JDK_ALLOCATION_NOT_COMPOSED,
    OUTPUT_OWNERSHIP_UNRESOLVED,
    ALLOCATION_ESCAPE_UNRESOLVED,
    HELPER_SPACE_EFFECT_INCOMPLETE,
    COLLECTION_GROWTH_UNRESOLVED,
    ALLOCATION_LIFETIME_UNRESOLVED,
    RECURSIVE_LIVE_ALLOCATION_UNSUPPORTED,
    MUTABLE_STATIC_STATE,
    GLOBAL_RETENTION_UNRESOLVED,
    WORKLIST_CONTAINER_UNRESOLVED,
    WORKLIST_MUTATION_UNRESOLVED,
    WORKLIST_CONSUMPTION_NOT_PROVEN,
    WORKLIST_STATE_UNIVERSE_UNRESOLVED,
    WORKLIST_ADMISSION_NOT_BOUNDED,
    WORKLIST_DUPLICATE_ADMISSION_POSSIBLE,
    ADMISSION_STATE_IDENTITY_UNRESOLVED,
    VISITED_MARKER_NOT_MONOTONIC,
    WORKLIST_CARDINALITY_UNRESOLVED,
    NEIGHBOR_BOUND_UNRESOLVED,
    GRAPH_EDGE_SUM_UNPROVEN,
    STRUCTURAL_PROOF_INCOMPLETE;

    /** Space-only reasons must not invalidate an otherwise complete time dimension (Batch 3+ closure). */
    public boolean blocksTimeAuthoritativeness() {
        return switch (this) {
            case JDK_ALLOCATION_NOT_COMPOSED, OUTPUT_OWNERSHIP_UNRESOLVED, ALLOCATION_ESCAPE_UNRESOLVED,
                    HELPER_SPACE_EFFECT_INCOMPLETE, COLLECTION_GROWTH_UNRESOLVED, ALLOCATION_LIFETIME_UNRESOLVED,
                    RECURSIVE_LIVE_ALLOCATION_UNSUPPORTED, MUTABLE_STATIC_STATE, GLOBAL_RETENTION_UNRESOLVED ->
                    false;
            default -> true;
        };
    }
}
