-- V4__complexity_analysis.sql — additive complexity analyzer persistence (Submission Service)

CREATE TABLE IF NOT EXISTS `complexity_analysis` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `analysis_id` varchar(36) NOT NULL,
  `submission_id` varchar(36) NOT NULL,
  `owner_user_id` varchar(255) NOT NULL,
  `question_id` bigint NOT NULL,
  `language` varchar(20) NOT NULL,
  `status` varchar(32) NOT NULL,
  `result_kind` varchar(32) DEFAULT NULL,
  `source_sha256` char(64) NOT NULL,
  `analysis_fingerprint` varchar(128) DEFAULT NULL,
  `reused_from_analysis_id` varchar(36) DEFAULT NULL,
  `profile_id` varchar(64) DEFAULT NULL,
  `profile_version` varchar(32) DEFAULT NULL,
  `profile_hash` char(64) DEFAULT NULL,
  `generator_version` varchar(32) DEFAULT NULL,
  `analyzer_version` varchar(32) DEFAULT NULL,
  `inference_version` varchar(32) DEFAULT NULL,
  `confidence_model_version` varchar(32) DEFAULT NULL,
  `knowledge_base_version` varchar(32) DEFAULT NULL,
  `harness_version` varchar(32) DEFAULT NULL,
  `measurement_policy_version` varchar(32) DEFAULT NULL,
  `profiler_runtime_version` varchar(32) DEFAULT NULL,
  `time_expression` varchar(255) DEFAULT NULL,
  `time_big_o` varchar(64) DEFAULT NULL,
  `time_bound_basis` varchar(32) DEFAULT NULL,
  `time_confidence` varchar(16) DEFAULT NULL,
  `space_expression` varchar(255) DEFAULT NULL,
  `space_big_o` varchar(64) DEFAULT NULL,
  `space_confidence` varchar(16) DEFAULT NULL,
  `limitations_json` json DEFAULT NULL,
  `variable_definitions_json` json DEFAULT NULL,
  `error_code` varchar(64) DEFAULT NULL,
  `attempt_count` int NOT NULL DEFAULT 0,
  `next_attempt_at` datetime(6) DEFAULT NULL,
  `lease_owner` varchar(64) DEFAULT NULL,
  `lease_expires_at` datetime(6) DEFAULT NULL,
  `active_slot` tinyint DEFAULT NULL,
  `requested_at` datetime(6) NOT NULL,
  `started_at` datetime(6) DEFAULT NULL,
  `completed_at` datetime(6) DEFAULT NULL,
  `updated_at` datetime(6) NOT NULL,
  `optimistic_version` bigint NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_complexity_analysis_id` (`analysis_id`),
  UNIQUE KEY `uk_complexity_submission_active_slot` (`submission_id`, `active_slot`),
  KEY `idx_complexity_owner_requested` (`owner_user_id`, `requested_at`),
  KEY `idx_complexity_submission_requested` (`submission_id`, `requested_at`),
  KEY `idx_complexity_status_next_attempt` (`status`, `next_attempt_at`),
  KEY `idx_complexity_reuse_lookup` (`submission_id`, `analysis_fingerprint`, `completed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `complexity_static_finding` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `analysis_id` varchar(36) NOT NULL,
  `category` varchar(64) NOT NULL,
  `source_start_line` int DEFAULT NULL,
  `source_end_line` int DEFAULT NULL,
  `expression` varchar(255) DEFAULT NULL,
  `certainty` varchar(32) DEFAULT NULL,
  `summary` varchar(512) NOT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_complexity_finding_analysis` (`analysis_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE IF NOT EXISTS `complexity_benchmark_run` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `analysis_id` varchar(36) NOT NULL,
  `case_id` varchar(64) NOT NULL,
  `variant` varchar(32) NOT NULL,
  `size_vector_json` json NOT NULL,
  `seed` bigint DEFAULT NULL,
  `input_hash` char(64) NOT NULL,
  `sample_count` int NOT NULL,
  `warmup_count` int NOT NULL,
  `median_elapsed_ns` bigint DEFAULT NULL,
  `mad_elapsed_ns` bigint DEFAULT NULL,
  `min_elapsed_ns` bigint DEFAULT NULL,
  `max_elapsed_ns` bigint DEFAULT NULL,
  `output_validated` bit(1) NOT NULL,
  `outcome` varchar(32) NOT NULL,
  `environment_fingerprint` varchar(128) DEFAULT NULL,
  `created_at` datetime(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_complexity_benchmark_analysis` (`analysis_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
